### ISSUE TITLE
关于P@N问题

### ISSUE THREAD

**Issue by xinbreeze** [ZhixiuYe/Intra-Bag-and-Inter-Bag-Attentions#5]
您好，我想请问一下关于P@N评测，按照代码中评测P@100应该是个整数，请问您论文中是实验多次取平均数吗？table 4中Lin2016的p@300数据好像打印错了

**Comment by ZhixiuYe** [comment]
对的，十次实验结果取的平均值。
确实打错了，是67.4，谢谢。
